name: Test Run

on:
  workflow_dispatch:

jobs:
  test-run:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Set build script permissions
        run: |
          chmod +x gradlew

      - name: Build JAR
        run: |
          ./gradlew build

      - name: Run Program
        id: run
        run: |
          java -jar build/libs/SampleSeleniumProject*.jar
        env:
          GITHUB_ACTIONS: ${{ github.actions }}